### ISSUE TITLE
Discord server packaging your Macros without any credit, accepting donations in return

### ISSUE THREAD

**Issue by Belgiancat** [waktool/RankQuests#41]
Noticed he had bundled A basement's Deeppoolmacro, made me look deeper into it. Seems like he steals other people's macros and bundles them in his .exe
Your macros are included inside of it.
https://discord.com/invite/hRR3HpJR5h
When confronted about it I was simply labeled a hater and promptly banned.

**Comment by DrMoPsycho** [comment]
- Chill, Waktool and I are working together.
- Second, check our deeppoolmacro it's a different code than the basement one and it's in version 2, not AHK version 1 like his, which is a totally different way of coding. I may have gotten the idea from the basement, but this is an entirely different code with libraries and everything. I hope you find something useful to do rather than just calling people out. Just go do something useful, bro.

**Comment by waktool** [comment]
@Belgiancat thanks for looking out for me, really appreciate that. I knew that project was using my macro. Under the GNU GENERAL PUBLIC LICENSE, they are allowed to reuse it (within the terms of the license) and not tell me, but they did tell me. I wanted my code to be opensource so everyone can learn from it. I have since joined the Psycho Hatcher development team. I like what they are doing, and I think it will help more players.
